service: my-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ca-central-1
  deploymentBucket:
    name: serverless-deployments-hamza.alaydi  # Replace with your bucket name
    serverSideEncryption: AES256
  environment:
    MONGODB_URI: ${env:MONGO_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    MAIL: ${env:MAIL}
    MAIL_PASSWORD: ${env:MAIL_PASSWORD}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}

package:
  patterns:
    - '!node_modules/.bin/**'  # Exclude unnecessary binaries
    - '!node_modules/**/test/**'  # Exclude test files
    - '!node_modules/**/docs/**'  # Exclude docs
    - '!node_modules/**/*.md'  # Exclude markdown files
    - '!node_modules/**/example*/**'  # Exclude example files
    - '!tests/**'
    - '!logs/**'
    - '!docs/**'
    - '!.*'

functions:
  my-backend-dev-app:
    handler: server.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-offline
