service: my-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ca-central-1
  environment:
    MONGO_URI: ${env:MONGO_URI}
    NODE_ENV: ${env:NODE_ENV}
    PORT: ${env:PORT}
    JWT_SECRET: ${env:JWT_SECRET}
    MAIL: ${env:MAIL}
    MAIL_PASSWORD: ${env:MAIL_PASSWORD}
    MAINTENANCE_SUPERVISOR_EMAIL: ${env:MAINTENANCE_SUPERVISOR_EMAIL}
    AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    AWS_REGION: ${env:AWS_REGION}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}

package:
  patterns:
    - "!node_modules/**"   # Exclude everything in node_modules
    - '!node_modules/.bin/**'  # ✅ Exclude unnecessary binaries
    - '!node_modules/**/test/**'  # ✅ Exclude test files
    - '!node_modules/aws-sdk/**'  # ✅ AWS SDK is included by default
    - '!node_modules/**/docs/**'  # ✅ Exclude docs
    - '!node_modules/**/*.md'  # ✅ Exclude markdown files
    - '!node_modules/**/example*/**'  # ✅ Exclude example files
    - '!tests/**'
    - '!logs/**'
    - '!docs/**'
    - '!.*'

functions:
  app:
    name: my-backend-dev-app
    handler: server.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-offline
  - serverless-dotenv-plugin
