service: my-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ca-central-1
  environment:
    MONGODB_URI: ${env:MONGO_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    MAIL: ${env:MAIL}
    MAIL_PASSWORD: ${env:MAIL_PASSWORD}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}

package:
  patterns:
    - '!node_modules/**'
    - '!tests/**'
    - '!.git/**'
    - '!logs/**'
    - '!docs/**'
    - '!.*'

functions:
  my-backend-dev-app:
    handler: server.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    exclude: ['aws-sdk']
    target: 'node20'
    platform: 'node'