service: my-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ca-central-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI}

package:
  patterns:
    - '!node_modules/.bin/**'  # Exclude unnecessary binaries
    - '!node_modules/**/test/**'  # Exclude test files in node_modules
    - '!.git/**'
    - '!tests/**'
    - '!logs/**'
    - '!docs/**'
    - '!.env'
    - '!.vscode/**'

functions:
  app:
    handler: server.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-offline
