service: my-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ca-central-1
  environment:
    MONGODB_URI: ${env:MONGODB_URI}

package:
  patterns:
    - '!node_modules/**'  # Exclude all node_modules
    - '!tests/**'  # Exclude tests
    - '!logs/**'  # Exclude logs
    - '!docs/**'  # Exclude documentation
    - '!.*'  # Exclude hidden files (.git, .vscode, .env)
    - '!src/**'  # Exclude source files (if not needed)
    - 'node_modules/aws-sdk/**'  # AWS SDK is included by default in Lambda

functions:
  app:
    handler: server.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-offline
