service: my-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ca-central-1
  deploymentBucket:
    name: serverless-deployments-hamza.alaydi # Replace with your S3 bucket name
    serverSideEncryption: AES256
  environment:
    MONGODB_URI: ${env:MONGO_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    MAIL: ${env:MAIL}
    MAIL_PASSWORD: ${env:MAIL_PASSWORD}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}

package:
  patterns:
    - '!node_modules/**'  # Exclude node_modules
    - '!tests/**'  # Exclude tests
    - '!.git/**'  # Exclude .git folder
    - '!logs/**'  # Exclude logs
    - '!docs/**'  # Exclude docs
    - '!.*'  # Exclude hidden files

functions:
  my-backend-dev-app:
    handler: server.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-offline
