service: my-backend

provider:
  name: aws
  runtime: nodejs20.x
  region: ca-central-1
  environment:
    MONGODB_URI: ${env:MONGO_URI}
    JWT_SECRET: ${env:JWT_SECRET}
    MAIL: ${env:MAIL}
    MAIL_PASSWORD: ${env:MAIL_PASSWORD}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}

package:
  individually: true  # Package each function separately
  patterns:
    - '!node_modules/**'  # Exclude node_modules (Webpack will handle dependencies)
    - '!tests/**'
    - '!logs/**'
    - '!docs/**'
    - '!.*'

functions:
  my-backend-dev-app:
    handler: .webpack/handler.handler  # Use the bundled handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-webpack  # Add Webpack plugin
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'  # Path to Webpack config
    includeModules: true  # Include external modules
