name: Deploy Serverless App

on:
  push:
    branches:
      - main  # Change this if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # Change this if needed
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./backend  # Adjust path if necessary

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your AWS region

      - name: Authenticate Serverless Framework
        run: serverless login --token ${{ secrets.SERVERLESS_ACCESS_KEY }}

      - name: Deploy Serverless Application
        run: serverless deploy
        working-directory: ./backend
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
