name: Deploy Backend
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Step 3: Navigate to backend directory
      - name: Move to backend directory
        run: cd backend

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      # Step 5: Install Serverless Framework locally (no global install needed)
      - name: Install Serverless
        run: npm install serverless

      # Step 6: Configure AWS credentials
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      # Step 7: Deploy to AWS Lambda
      - name: Deploy with Serverless
        run: npx serverless deploy
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
