name: Deploy Backend to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install dependencies
      - name: Install dependencies
        run: |
          npm install --production
          npm cache clean --force

      # Step 3: Prepare EC2 directory
      - name: Prepare EC2 Directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo rm -rf /var/www/stephan-backend
            sudo mkdir -p /var/www/stephan-backend
            sudo chown -R ubuntu:ubuntu /var/www/stephan-backend
            sudo chmod -R 755 /var/www/stephan-backend

      # Step 4: Deploy backend code to EC2
      - name: Deploy Backend Code
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/var/www/stephan-backend"
          overwrite: true
          strip_components: 0
          debug: true

      # Step 5: Configure permissions and restart the backend
      - name: Configure Permissions and Restart Backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/stephan-backend
            npm install --production
            pm2 restart stephan-backend