name: Deploy Backend to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install --production
          npm cache clean --force

      - name: Deploy Code
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/var/www/stephan-backend"
          exclude: |
            .env
            .git
            .github
            node_modules

      - name: Restart Service
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Fix permissions
            sudo chown -R ubuntu:ubuntu /var/www/stephan-backend

            # Install dependencies
            cd /var/www/stephan-backend
            npm install --production

            # PM2 management
            if ! pm2 list | grep -q stephan-backend; then
              pm2 start ecosystem.config.js
              pm2 save
              pm2 startup ubuntu -u ubuntu
            else
              pm2 reload ecosystem.config.js --update-env
            fi

            # Persist process list
            pm2 save
