name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Deploy
        uses: appleboy/ssh-action@main # Or a specific tag like @v4.0.0
        with:
          host: 35.183.45.108
          username: ubuntu
          key: -----BEGIN OPENSSH PRIVATE KEY----- b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtz c2gtZWQyNTUxOQAAACApd5RMFlPJ3aLD4mZImVl2jrUjU6FRdg97SwkA91CXZAAA AIjtLRhX7S0YVwAAAAtzc2gtZWQyNTUxOQAAACApd5RMFlPJ3aLD4mZImVl2jrUj U6FRdg97SwkA91CXZAAAAEAwUQIBATAFBgMrZXAEIgQgQr6OLL163yyMKoNuwuSi YCl3lEwWU8ndosPiZkiZWXaOtSNToVF2D3tLCQD3UJdkAAAAAAECAwQF -----END OPENSSH PRIVATE KEY-----
          script: |
            cd /var/www/html/Stephan-management-back # The correct path on your EC2 instance
            git pull origin main
            npm install --production
            pm2 startOrRestart app.js --node-args="--experimental-modules" --name my-app
            sudo systemctl reload nginx  # Only if using Nginx
