name: Deploy Backend to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install dependencies locally
      - name: Install dependencies
        run: |
          npm install --production
          npm cache clean --force

      # Step 3: Backup .env file before deleting the directory
      - name: Backup .env file
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Remove immutability flag if set
            sudo chattr -i /var/www/stephan-backend/.env || true
            # Backup .env
            sudo cp /var/www/stephan-backend/.env /tmp/.env || true
            # Clean up directory
            sudo rm -rf /var/www/stephan-backend
            sudo mkdir -p /var/www/stephan-backend
            sudo chown -R ubuntu:ubuntu /var/www/stephan-backend
            sudo chmod -R 755 /var/www/stephan-backend

      # Step 4: Deploy backend code to EC2 (EXCLUDING .env)
      - name: Deploy Backend Code
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          source: "."
          target: "/var/www/stephan-backend"
          overwrite: true
          strip_components: 0
          exclude: |
            .env
            .gitignore
            .github/

      # Step 5: Restore .env file and restart backend
      - name: Restore .env file and Restart Backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Restore .env
            sudo cp /tmp/.env /var/www/stephan-backend/.env || true
            sudo chmod 644 /var/www/stephan-backend/.env
            # Reapply immutability flag
            sudo chattr +i /var/www/stephan-backend/.env || true
            # Install and restart
            cd /var/www/stephan-backend
            npm install --production
            pm2 restart stephan-backend --update-env

