name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Deploy
        uses: appleboy/ssh-action@main
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/html/Stephan-management-back  # **Correct Path on EC2**
            git pull origin main
            npm install --production # Install only production dependencies
            pm2 startOrRestart app.js --node-args="--experimental-modules" --name my-app # Use startOrRestart and a name
            sudo systemctl reload nginx # Only if using Nginx
